### PR TITLE
Update mongoose to v4

### PR DESCRIPTION
**Pull request by iliakan**
Update mongoose, remove bluebird as it's not needed any more.
Bluebird is old anyway!

### CODE REVIEW

**Comment by rfink** [comment]
Hey, thanks very much for the contribution.  Are you using my fork in lieu of the source?

**Comment by iliakan** [comment]
Hi, oh I'm not sure what I used.

Of course I'd prefer it to be merged into the published koa-session-mongoose.

**Comment by rfink** [comment]
I'm happy to merge changes in with my fork, but if you want to use the published version, I'd recommend publishing a PR to them as well. I'm not sure the source is still maintained, however.

**Comment by iliakan** [comment]
yeah me too, I had to use your fork for some reason long ago

**Pull request merged**
